services:
    geyser_plugin_solana:
        container_name: simo_geyser_plugin_solana
        build:
            context: ./service/solana
            dockerfile: dockerfile
        ports:
        - 10000:10000
        volumes:
            - ./../../../:/simo/geyser_plugin
        restart: always
        tty: true
        init: true
networks:
    default:
        external: true
        name: simo_geyser_plugin