FROM rust:1.78.0

RUN \
mkdir -p /simo/geyser_plugin && \
rustup default stable && \
rustup toolchain install nightly && \
rustup component add --toolchain=stable \
    clippy \
    rust-src && \
rustup component add --toolchain=nightly-x86_64-unknown-linux-gnu \
    rustfmt
