services:
    server_rust_stable_toolchain:
        container_name: simo_server_rust_stable_toolchain
        build:
            context: ./service/rust_stable_toolchain/
            dockerfile: dockerfile
        environment:
            USER: ${USER}
        volumes:
            - ./../../../../../:/simo
        working_dir: /simo
        restart: always
        tty: true
        init: true
networks:
    default:
        name: simo_server
        driver: bridge